---
- name: Install nginx
  hosts: webserver
  remote_user: root
  tasks:
    - name: Install Nginx
      apt:
        name: nginx-extras
        update_cache: false

    - name: Start nginx service
      systemd:
        name: nginx
        state: started

    - name: Update nginx config
      copy:
        src: ./defaul-site.conf
        dest: /etc/nginx/sites-enabled/default
        mode: 0644
      notify: nginx -s reload
