---
- name: Add psql repository key
  apt_key: 
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Install repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt bionic-pgdg main"

- name: Install psql
  apt:
    name:
      - "postgresql-{{ postgres_version }}"
    update_cache: yes
  ignore_errors: "{{  ansible_check_mode  }}"

- name: Update psql config
  copy:
    src: ./roles/posgres_db/templates/postgresql.conf.sample
    dest: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf.sample
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
    mode: 0644

- name: Check psql configs
  become: yes
  become_method: sudo
  become_user: postgres
  shell: "psql -f ./roles/posgres_db/templates/check-configuration.sql"
  register: psql_config_status

- name: psql test status
  debug:
    msg: "{{ psql_config_status }}"

- name: Make sure psycopg2 is installed
  pip:
    name: psycopg2
    state: present

- name: reset database user
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_user: 
    db: postgres
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
    #password: "{{ postgres_password | password_hash('sha512') }}"
    #encrypted: yes

- name: create database user
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_user: 
    db: postgres
    name: "mytestuser"
    password: "{{ postgres_password }}"
    #password: "{{ postgres_password | password_hash('sha512') }}"
    #priv: ALL:SELECT,INSERT,UPDATE,DELETE,CONNECT
    role_attr_flags: "SUPERUSER"
    #encrypted: yes
