- hosts: webserver
  become: true
  gather_facts: false
  pre_tasks:
  - name: 'install python'
    raw: 'sudo apt-get -y install python'
  - no-changed-when  # Commands should not change things if nothing needs doing
