---
- name: Install nginx
  hosts: webserver
  remote_user: root
  tasks:
    - name: Install Nginx
      apt:
        name: nginx-extras
        update_cache: no

    - name: Start nginx service
      systemd:
        name: nginx
        state: started

    - name: Update nginx config
      copy:
        src: ./defaul-site.conf
        dest: /etc/nginx/sites-enabled/default
        mode: 0644

    - name: Check NGINX configs
      shell: "/usr/sbin/nginx -t"
      register: nginx_config_status

    - name: NGINX test status
      debug:
        msg: "{{ nginx_config_status }}"

    - name: Service NGINX restart and enable on boot
      systemd:
        name: nginx
        state: restarted
        #enabled: yes
        daemon_reload: yes
      when: nginx_config_status.rc == 0
