version: "2"
services:
  nginx:
    image: dvin/nginx:1.0.1
    container_name: nginx
    volumes:
      - ./headers.conf:/etc/nginx/conf.d/headers.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - ENV_INFO=${ENV_INFO}
      - GitConnectionString=${GitConnectionString}
#    ports:
#      - "8081:8080"
#    entrypoint:
#          - sh
#          - -c
#          - "while [ 1 ]; do echo . ; sleep 5; done"
