---
- name: Install packages - Ubuntu
  apt:
    name: "{{  item }}"
    update_cache: yes
    autoremove: yes
  with_items:
    - htop
    - python-pip
    - python-setuptools
    - python-dev
    - gcc
    - python-psycopg2
  when: ansible_os_family == 'Debian'
- name: Install packages - RedHat
  yum:
    name: "{{  package_item }}"
    update_cache: yes
    autoremove: yes
  with_items:
    - python-pip
    - python-setuptools
    - python-dev
  when: ansible_os_family == 'RedHat'
