name: Terraform

on:  
  push:
    paths:
    - 'terraform2/**'
  pull_request:
    branches:
      - master

jobs:
  tf:
    name: tf
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check dir
      run: ls

    - name: check tf
      uses:  dvyu/devops_course_terraform@main
      env:
        WORKDIR: ./terraform2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: check ansible
      uses:  dvyu/devops_course_ansible@main
      env:
        WORKDIR: ./ansible/first-example
